# .peavers.yml - Addon metadata for peavers.io website

# Featured addon appears prominently on homepage
featured: true

# Icon to display on website
iconType: CurrencyRuneIcon

# CurseForge project ID for download statistics
curseForgeProjectId: 1266922

# Tags for filtering and categorization
tags:
  - currency
  - tooltip
